[package]
name = "kaspa-wrpc-wasm"
description = "Kaspa wRPC WASM client"
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[features]
wasm32-sdk = ["kaspa-wrpc-client/wasm32-sdk"]

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
kaspa-wrpc-client.workspace = true
