[package]
name = "kaspa-wrpc-example-subscriber"
description = "Kaspa wRPC subscription example"
publish = false
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
# async-trait.workspace = true
# clap.workspace = true
futures.workspace = true
kaspa-consensus-core.workspace = true
# kaspa-grpc-client.workspace = true
kaspa-rpc-core.workspace = true
kaspa-wrpc-client.workspace = true
kaspa-notify.workspace = true
tokio.workspace = true
# kaspa-rpc-macros.workspace = true
# kaspa-wrpc-server.workspace = true
# num_cpus.workspace = true
# thiserror.workspace = true
# tokio.workspace = true
workflow-core.workspace = true
workflow-log.workspace = true
ctrlc.workspace = true
# workflow-rpc.workspace = true
